apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: secret-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv
  target:
    name: demo-secret
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: demo-secret
