apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-kv
  namespace: secret-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: "85c4f090-d8d8-4aec-a410-e81b4d0b745c"
      vaultUrl: "https://kv-bm-platform-dev.vault.azure.net"
      serviceAccountRef:
        name: kv-reader
